### ISSUE TITLE
Outline goal of unit overhaul....

### ISSUE THREAD

**Issue by jklymak** [matplotlib/2020-NASA-ROSES-E7#1]
Hi, nice start and the outline looks good.  

The text seems to say that we simply need to document units and add testing.  a) that won't make for a super compelling proposal, and b) I think the system needs significantly more work than that.

I'd suggest folks can feel free to edit this and add issues with units.  I'll also point to the existing issues https://github.com/matplotlib/matplotlib/issues?q=is%3Aopen+is%3Aissue+label%3Aunits

Suggested things to propose to work on

- Collate examples of downstream libraries that use units and document
- Realize the goal of being able to change the units of an axis.  i.e. allow the user to toggle meters or inches, and not have to change the input data; this was the original goal of units `ax.xaxis.set_units()` is completely broken: https://github.com/matplotlib/matplotlib/issues/5051, https://matplotlib.org/examples/units/units_scatter.html  https://github.com/matplotlib/matplotlib/issues/9713
- Related to the above, unit conversion would ideally be invertible in locations where we store x and y data.  This probably requires engineering a container, but by doing so we could remove a lot of pain points in the code.  (https://github.com/matplotlib/matplotlib/issues/8072, probably all the categorical code, would be helpful for datetime as well)

My guess is that a proper re-engineering of units would be a huge help, but also substantial dedicated work.  Given that NASA are the primary units users, I think it is great that they may contribute to helping fix this issue.

**Comment by tacaswell** [comment]
@jklymak I fleshed out the section on the unit work.  It is still tilted towards the doc / testing effort, but includes a paragraph about extending the functionality.

**Comment by jklymak** [comment]
Great.  But my main point is that the original functionality was broken at some point and either needs to be fixed or removed.
